package me.eumenides.dao;

import java.util.List;
import me.eumenides.entity.SysRolePerm;
import me.eumenides.entity.SysRolePermExample;
import org.apache.ibatis.annotations.Param;

public interface SysRolePermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_perm
     *
     * @mbggenerated
     */
    int countByExample(SysRolePermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_perm
     *
     * @mbggenerated
     */
    int deleteByExample(SysRolePermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_perm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer rolePermId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_perm
     *
     * @mbggenerated
     */
    int insert(SysRolePerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_perm
     *
     * @mbggenerated
     */
    int insertSelective(SysRolePerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_perm
     *
     * @mbggenerated
     */
    List<SysRolePerm> selectByExample(SysRolePermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_perm
     *
     * @mbggenerated
     */
    SysRolePerm selectByPrimaryKey(Integer rolePermId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_perm
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysRolePerm record, @Param("example") SysRolePermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_perm
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysRolePerm record, @Param("example") SysRolePermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_perm
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRolePerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_perm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRolePerm record);
}