package me.eumenides.entity;

public class SysRolePerm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_perm.role_perm_id
     *
     * @mbggenerated
     */
    private Integer rolePermId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_perm.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_perm.perm_id
     *
     * @mbggenerated
     */
    private Integer permId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_perm.role_perm_id
     *
     * @return the value of sys_role_perm.role_perm_id
     *
     * @mbggenerated
     */
    public Integer getRolePermId() {
        return rolePermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_perm.role_perm_id
     *
     * @param rolePermId the value for sys_role_perm.role_perm_id
     *
     * @mbggenerated
     */
    public void setRolePermId(Integer rolePermId) {
        this.rolePermId = rolePermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_perm.role_id
     *
     * @return the value of sys_role_perm.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_perm.role_id
     *
     * @param roleId the value for sys_role_perm.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_perm.perm_id
     *
     * @return the value of sys_role_perm.perm_id
     *
     * @mbggenerated
     */
    public Integer getPermId() {
        return permId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_perm.perm_id
     *
     * @param permId the value for sys_role_perm.perm_id
     *
     * @mbggenerated
     */
    public void setPermId(Integer permId) {
        this.permId = permId;
    }
}